import type { NodeType, VerificationMode } from '../../types/node.types'
import type { AIProviderConfig } from '../../types/ai.types'
import { chat } from './client'

export interface ClassificationResult {
  nodeType: NodeType
  verificationMode: VerificationMode
  label: string
}

export interface AutoGeneratedNode {
  label: string
  nodeType: NodeType
  verificationMode: VerificationMode
  reason?: string
}

const TYPE_TO_MODE: Record<NodeType, VerificationMode> = {
  concept: 'sync_block',
  logic: 'sync_block',
  fact: 'async_parallel',
  unclear: 'immediate_interrupt'
}

function normalizeNodeLabel(raw: string): string {
  return raw
    .replace(/^[-*•#]+\s*/, '')
    .replace(/^[0-9]+\.\s*/, '')
    .replace(/\s+/g, ' ')
    .trim()
}

function dedupeNodes(nodes: AutoGeneratedNode[], maxNodes: number): AutoGeneratedNode[] {
  const seen = new Set<string>()
  const result: AutoGeneratedNode[] = []

  for (const node of nodes) {
    const label = normalizeNodeLabel(node.label)
    if (!label) continue
    const key = label.toLowerCase()
    if (seen.has(key)) continue
    seen.add(key)
    result.push({
      label,
      nodeType: node.nodeType,
      verificationMode: node.verificationMode || TYPE_TO_MODE[node.nodeType]
    })
    if (result.length >= maxNodes) break
  }

  return result
}

/**
 * Classify a single cue line as a node type using AI.
 * Falls back to 'concept' if AI call fails or is unavailable.
 */
export async function classifyNode(
  cueText: string,
  topic: string,
  provider: AIProviderConfig | null
): Promise<ClassificationResult> {
  // Clean up the cue text
  const label = cueText.replace(/^[-*•]\s*/, '').replace(/\[node:[^\]]+\]/g, '').trim()

  if (!label || !provider) {
    return { nodeType: 'concept', verificationMode: 'sync_block', label: label || cueText }
  }

  const prompt = `你是一个知识分类专家。判断以下知识点属于哪种类型：

知识点：「${label}」
所属主题：${topic}

类型定义：
- concept：纯概念定义（如"什么是惯性"）
- logic：需要推导/有因果关系的逻辑知识（如"F=ma的推导"、"为什么动量守恒"）
- fact：具体事实数据（如"光速约为3×10⁸m/s"、"牛顿生于1643年"）
- unclear：表述模糊，需要用户先澄清

只返回 JSON，不要其他文字：
{"nodeType": "concept|logic|fact|unclear", "reasoning": "一句话原因"}`

  try {
    const response = await chat(provider, [
      { role: 'user', content: prompt }
    ])

    const cleaned = response.replace(/^```(?:json)?\s*/m, '').replace(/\s*```$/m, '').trim()
    const parsed = JSON.parse(cleaned)
    const nodeType: NodeType = ['concept', 'logic', 'fact', 'unclear'].includes(parsed.nodeType)
      ? parsed.nodeType
      : 'concept'

    return {
      nodeType,
      verificationMode: TYPE_TO_MODE[nodeType],
      label
    }
  } catch {
    return { nodeType: 'concept', verificationMode: 'sync_block', label }
  }
}

/**
 * Extract knowledge nodes from cues section without AI (heuristic fallback).
 * Used when no AI provider is configured.
 */
export function extractNodesFromCues(cuesText: string): string[] {
  return cuesText
    .split('\n')
    .filter(line => /^[-*•]/.test(line.trim()) || /^#{1,3}\s/.test(line.trim()))
    .map(line => line.replace(/^[-*•#]+\s*/, '').replace(/\[node:[^\]]+\]/g, '').trim())
    .filter(Boolean)
    .slice(0, 20) // Max 20 nodes per note
}

/**
 * Generate knowledge nodes from note content with AI.
 * The model is encouraged to "summarize then summarize again" before emitting final nodes.
 */
export async function generateNodesFromLearningContent(
  params: {
    topic: string
    cues: string
    notes: string
    summary: string
    provider: AIProviderConfig | null
    maxNodes?: number
  }
): Promise<AutoGeneratedNode[]> {
  const {
    topic,
    cues,
    notes,
    summary,
    provider,
    maxNodes = 10
  } = params

  const fallbackLabels = extractNodesFromCues([cues, notes].join('\n')).slice(0, maxNodes)
  const fallbackNodes: AutoGeneratedNode[] = fallbackLabels.map((label) => ({
    label,
    nodeType: 'concept',
    verificationMode: 'sync_block'
  }))

  if (!provider) {
    return fallbackNodes
  }

  const prompt = `你是“费曼学习法”知识图谱助手。请根据用户笔记自动构建待验证知识节点。

要求：
1) 先在内部做两轮总结（提炼核心 -> 再压缩为可验证节点），但不要输出你的思考过程。
2) 每个节点必须简洁、可被学生提问验证，长度控制在 6~20 字。
3) 节点类型必须使用：
- concept（概念定义）
- logic（推导/因果/算法逻辑）
- fact（事实/数据/结论）
- unclear（表达模糊需澄清）
4) 验证模式映射：
- concept/logic -> sync_block
- fact -> async_parallel
- unclear -> immediate_interrupt
5) 去重，避免同义重复，最多返回 ${maxNodes} 个。

只返回 JSON，不要任何额外文本。格式：
{
  "nodes": [
    {
      "label": "节点名称",
      "nodeType": "concept|logic|fact|unclear",
      "verificationMode": "sync_block|async_parallel|immediate_interrupt",
      "reason": "一句话原因"
    }
  ]
}

主题：${topic || '未指定'}

Cues:
${cues || '（空）'}

Notes:
${notes || '（空）'}

Summary:
${summary || '（空）'}`

  try {
    const response = await chat(provider, [{ role: 'user', content: prompt }])
    const cleaned = response.replace(/^```(?:json)?\s*/m, '').replace(/\s*```$/m, '').trim()
    const parsed = JSON.parse(cleaned)

    const rawNodes: unknown[] = Array.isArray(parsed)
      ? parsed
      : Array.isArray(parsed?.nodes)
        ? parsed.nodes
        : []

    const candidateNodes: AutoGeneratedNode[] = rawNodes
      .map((item): AutoGeneratedNode | null => {
        if (!item || typeof item !== 'object') return null
        const maybeLabel = normalizeNodeLabel(String((item as any).label || ''))
        const maybeType = String((item as any).nodeType || '')
        const nodeType: NodeType = ['concept', 'logic', 'fact', 'unclear'].includes(maybeType)
          ? (maybeType as NodeType)
          : 'concept'
        const modeRaw = String((item as any).verificationMode || '')
        const verificationMode: VerificationMode =
          ['sync_block', 'async_parallel', 'immediate_interrupt'].includes(modeRaw)
            ? (modeRaw as VerificationMode)
            : TYPE_TO_MODE[nodeType]

        if (!maybeLabel) return null
        return {
          label: maybeLabel,
          nodeType,
          verificationMode,
          reason: typeof (item as any).reason === 'string' ? (item as any).reason : undefined
        }
      })
      .filter((item): item is AutoGeneratedNode => item !== null)

    const normalized = dedupeNodes(candidateNodes, maxNodes)
    if (normalized.length > 0) return normalized
    return fallbackNodes
  } catch {
    return fallbackNodes
  }
}
