export const IPC = {
  FS_READ_NOTE: 'fs:read-note',
  FS_WRITE_NOTE: 'fs:write-note',
  FS_LIST_NOTEBOOKS: 'fs:list-notebooks',
  FS_CREATE_NOTEBOOK: 'fs:create-notebook',
  FS_CREATE_NOTE: 'fs:create-note',
  FS_DELETE_NOTE: 'fs:delete-note',
  FS_READ_INDEX: 'fs:read-index',
  FS_WRITE_INDEX: 'fs:write-index',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
  DIALOG_OPEN_DIRECTORY: 'dialog:open-directory',
  CHAT_HISTORY_GET: 'chat-history:get',
  CHAT_HISTORY_SET: 'chat-history:set',
  CHAT_HISTORY_DELETE: 'chat-history:delete',
  CHAT_HISTORY_CLEAR: 'chat-history:clear',
  RAG_INDEX_NOTE: 'rag:index-note',
  RAG_DELETE_NOTE: 'rag:delete-note',
  RAG_SEARCH: 'rag:search',
  RAG_UPLOAD_FILE: 'rag:upload-file',
  RAG_LIST_FILES: 'rag:list-files',
  RAG_DELETE_FILE: 'rag:delete-file',
} as const
